spring: 
  datasource: 
    url: ${DATABASE_URL:jdbc:mysql://mybdb.cddkgvwhc4hh.us-east-1.rds.amazonaws.com/mybdb}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER:admin}
    password: ${DATABASE_PASSWORD:F1Avin_duPn3u}
  jpa: 
    hibernate: 
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQLDialect
        

cipher:
  key: ${CIPHER_KEY:Bar12345Bar12345}
  type: ${CIPHER_TYPE_INSTANCE:AES/ECB/PKCS5PADDING}

server:
  port: 8080