spring: 
  datasource: 
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa: 
    hibernate: 
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.MySQLDialect
        

cipher:
  key: ${CIPHER_KEY}
  type: ${CIPHER_TYPE_INSTANCE}

server:
  port: 8080